name: SEC Form D Daily Pull

on:
  schedule:
    # Runs at 7 AM EST (12:00 UTC) Monday-Friday
    # SEC updates data overnight, so morning pull gets previous day's filings
    - cron: '0 12 * * 1-5'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      lookback_days:
        description: 'Number of days to look back'
        required: false
        default: '1'

env:
  CLAY_WEBHOOK_URL: ${{ secrets.CLAY_WEBHOOK_URL }}
  SEC_USER_AGENT: ${{ secrets.SEC_USER_AGENT }}
  MIN_OFFERING: 2000000
  MAX_OFFERING: 6000000

jobs:
  pull-form-d:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run Form D puller
        env:
          CLAY_WEBHOOK_URL: ${{ secrets.CLAY_WEBHOOK_URL }}
          SEC_USER_AGENT: ${{ secrets.SEC_USER_AGENT }}
          LOOKBACK_DAYS: ${{ github.event.inputs.lookback_days || '1' }}
        run: |
          python sec_form_d_puller.py
      
      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: form-d-results-${{ github.run_id }}
          path: |
            *.json
            *.log
          retention-days: 30
